- README.md
- specification/proxygen.yaml
> Apm 4453 spec improvements

- .github/workflows/pr-lint.yaml
- specification/proxygen.yaml
> Update proxygen.yaml - content review

- specification/proxygen.yaml
> APM-4465. Add details to the UAT specification routes.

- .gitignore
- specification/proxygen.yaml
* Routine Change - minor wording changes
> Initial suggestions

- .github/workflows/publish-uat.yml
- specification/proxygen.yaml
> APM-4451 Temporary instances cant be nhsd-prod envs

- .github/workflows/pr-lint.yaml
- .github/workflows/publish-uat.yml
- specification/components/schemas/proxygen-oas.yaml
- specification/proxygen.yaml
> APM-4483 MTLS changes

- specification/proxygen.yaml
> APM-4430: Describe API Instance Limits

- specification/proxygen.yaml
> APM-4664 API config endpoints

- specification/proxygen.yaml
(But unfortunately still not rendering properly)
> APM-4646: Fix paths in `x-spec-publication`

- specification/proxygen.yaml
> APM-4773: empty object recommendation

- .github/workflows/pr-lint.yaml
- specification/proxygen.yaml
> feature/PI-109-forward-attributes added information about target-attributes to spec

- Makefile
- specification/proxygen.yaml
> APM-4586 update proxygen spec

- .github/workflows/pr-lint.yaml
- .github/workflows/publish-uat.yml
- .github/workflows/release.yml
- Makefile
> Apm 0000 repo improvements

- specification/proxygen.yaml
> AEA-3787 Add target identity options to Proxygen

- specification/proxygen.yaml
> APM-5160 Reorder target identity section

- specification/proxygen.yaml
> APM-5266 NHS login target header forwarding

- specification/proxygen.yaml
> APM-5265 updates for id token identity header option

- specification/proxygen.yaml
> Apm 5268 adding cis2 acr to target identity

- specification/proxygen.yaml
> APM-5256: Add identity proofing level

- pyproject.toml
> APM-6142 set package mode false

- .github/workflows/sbom.yml
- scripts/create-sbom.sh
- scripts/update-sbom.py
> sbom congiuration
